/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Module3RouteImport } from './routes/module3'
import { Route as Module2RouteImport } from './routes/module2'
import { Route as Module1RouteImport } from './routes/module1'
import { Route as HallRouteImport } from './routes/hall'
import { Route as IndexRouteImport } from './routes/index'

const Module3Route = Module3RouteImport.update({
  id: '/module3',
  path: '/module3',
  getParentRoute: () => rootRouteImport,
} as any)
const Module2Route = Module2RouteImport.update({
  id: '/module2',
  path: '/module2',
  getParentRoute: () => rootRouteImport,
} as any)
const Module1Route = Module1RouteImport.update({
  id: '/module1',
  path: '/module1',
  getParentRoute: () => rootRouteImport,
} as any)
const HallRoute = HallRouteImport.update({
  id: '/hall',
  path: '/hall',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hall': typeof HallRoute
  '/module1': typeof Module1Route
  '/module2': typeof Module2Route
  '/module3': typeof Module3Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hall': typeof HallRoute
  '/module1': typeof Module1Route
  '/module2': typeof Module2Route
  '/module3': typeof Module3Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/hall': typeof HallRoute
  '/module1': typeof Module1Route
  '/module2': typeof Module2Route
  '/module3': typeof Module3Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/hall' | '/module1' | '/module2' | '/module3'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/hall' | '/module1' | '/module2' | '/module3'
  id: '__root__' | '/' | '/hall' | '/module1' | '/module2' | '/module3'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HallRoute: typeof HallRoute
  Module1Route: typeof Module1Route
  Module2Route: typeof Module2Route
  Module3Route: typeof Module3Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/module3': {
      id: '/module3'
      path: '/module3'
      fullPath: '/module3'
      preLoaderRoute: typeof Module3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/module2': {
      id: '/module2'
      path: '/module2'
      fullPath: '/module2'
      preLoaderRoute: typeof Module2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/module1': {
      id: '/module1'
      path: '/module1'
      fullPath: '/module1'
      preLoaderRoute: typeof Module1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hall': {
      id: '/hall'
      path: '/hall'
      fullPath: '/hall'
      preLoaderRoute: typeof HallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HallRoute: HallRoute,
  Module1Route: Module1Route,
  Module2Route: Module2Route,
  Module3Route: Module3Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
